apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded MongoDB URI from values file
  mongodb-uri: {{ .Values.config.mongoDbUri | b64enc | quote }}
