apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-demo-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Source repository URL (should be updated with user's Git repo URL)
    repoURL: 'https://github.com/chicmic/eks-task.git'
    targetRevision: HEAD
    path: helm/frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
