apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: argocd.vivekkumarsingh.online
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - argocd.vivekkumarsingh.online
      secretName: argocd-tls-secret
  rules:
    - host: argocd.vivekkumarsingh.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80